services:
  chatbot:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "chatbot"
      OLLAMA_URL: "http://ollama:11434"
    depends_on:
      - mysql
#        condition: service_healthy
#      ollama:
#        condition: service_healthy

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatbot
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
#    entrypoint: ["/bin/sh", "-c", "ollama pull llama3 && ollama serve"]  # 让 Ollama 自动下载 Llama 3
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 10s
      retries: 5
    restart: always

volumes:
  mysql_data:
  ollama_data: