// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"chatbot/api/handler"
	"chatbot/internal/ioc"
	"chatbot/internal/repository"
	"chatbot/internal/repository/dao"
	"chatbot/internal/service/dialogue"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	dialogueDAO := dao.NewDialogueDAO(db)
	dialogueRepository := repository.NewDialogueRepository(dialogueDAO)
	client := ioc.InitLLMClient()
	service := dialogue.NewDialogueService(dialogueRepository, client)
	chatHandler := handler.NewChatHandler(service)
	modelsHandler := handler.NewModelsHandler()
	historyHandler := handler.NewHistoryHandler()
	clearHandler := handler.NewClearHandler()
	app := ioc.NewApp(chatHandler, modelsHandler, historyHandler, clearHandler)
	return app
}

// wire.go:

var (
	BaseSet = wire.NewSet(ioc.InitDB, ioc.InitLLMClient)

	dialogueSvcSet = wire.NewSet(dao.NewDialogueDAO, repository.NewDialogueRepository, dialogue.NewDialogueService)

	handlersSet = wire.NewSet(handler.NewChatHandler, handler.NewModelsHandler, handler.NewHistoryHandler, handler.NewClearHandler)
)
